### ISSUE TITLE
.sdkrc to store versions for specific directory

### ISSUE THREAD

**Issue by marc0der** [sdkman/sdkman-extensions#9]
@musketyr commented on [Tue Aug 30 2016](https://github.com/sdkman/sdkman-cli/issues/463)

I would be great if there is alternative to `.nvmrc` file in [NVM](https://github.com/creationix/nvm).

Given `.sdkrc` file in current directory with following content

```
grails=3.2.0.M2
```

When I run `sdk use`
Then `grails` version `3.2.0.M2` is downloaded if not present yet
And `grails` version `3.2.0.M2` is used in current shell

---

@marc0der commented on [Wed Aug 31 2016](https://github.com/sdkman/sdkman-cli/issues/463#issuecomment-243752839)

This is already mostly supported in the [sdkman-extensions](https://github.com/sdkman/sdkman-extensions) project by way of the `sdk switch` command. Feel free to give it a try and/or raise any PRs on this to improve it.

---

@musketyr commented on [Wed Aug 31 2016](https://github.com/sdkman/sdkman-cli/issues/463#issuecomment-243756761)

this looks it's doing way too much magic and does not work for every candidate supported. I would prefer having separate file. let's keep this option open.

---

@marc0der commented on [Wed Aug 31 2016](https://github.com/sdkman/sdkman-cli/issues/463#issuecomment-243757591)

For sure, it's not in a great state.
Is that you volunteering to write a new extension? :-)

---

@marc0der commented on [Wed Aug 31 2016](https://github.com/sdkman/sdkman-cli/issues/463#issuecomment-243757790)

Moving this issue over to the sdkman-extensions project, as this will not be implemented in the CLI.

**Comment by reitzig** [comment]
What is the state on this?

Had the same thought today. Since "[SDKMAN!] was inspired by the very useful RVM and rbenv tools", it seems natural to expect that it would be easy to set up per-project settings.

**Comment by marc0der** [comment]
Feel free to write an extension that will perform the switching. What makes sdkman different from the likes of rvm is that it is completely agnostic of what it's serving so the sdkman core cannot be coupled to one specific technology.

**Comment by reitzig** [comment]
Maybe I misunderstood above discussion; I for one wasn't thinking about coupling to any specific technology. I was thinking, how do I use sdkman to say, 

 * "always use Java 8 for this here project, but Java 10 for that other one"  
  (useful for development multiple projects, each with different SDK dependencies), or 
 * "install exactly the SDKs this project needs, into the current directory, and then use those"  
  (useful for CI build environments that don't use Docker or similar).

For the config part, having a file like e.g. a Gemfile in the project repo, let's call it `.sdkman`, seems prudent. It could look as simple as this:

```
java 8.0.181-oracle
gradle 4.9
```

Some command would check the path for such a file, chdir there, install what's needed, and `use` them. (Arguably, `sdk install` would be a good choice since that's what other tools use, but would probably break expectations of sdkman users, who are used to sdkman acting user-globally.)

For the "install into the current folder" part, I think temporarily changing `SDKMAN_CANDIDATES_DIR` should do the job.

> Feel free to write an extension that will perform the switching

Fair enough; what's your timeline on that rewrite? Even if I need this enough at some point to sit down and write it, I'd hate to wrestle with Bash only to have the effort evaporate shortly thereafter.

**Comment by reitzig** [comment]
Ohhh, `sdk-switch` is specific to Gradle! I was mislead by the title and general gist of the issue, my bad.
My feature request/idea/brainstorm stands, though. :)

**Comment by marc0der** [comment]
Closing this in favour of https://github.com/sdkman/sdkman-cli/issues/683
